### ISSUE TITLE
Trouble running final-installation-steps.sh

### ISSUE THREAD

**Issue by fordmadox** [rsdoiel/archivesspace-api-workshop#2]
Whenever I attempt to run the final-installation-steps.sh command, I get the following error:

```
vagrant@vagrant:/$ sh /vagrant/final-installation-steps.sh
: not foundnal-installation-steps.sh: 4: /vagrant/final-installation-steps.sh:
/vagrant/final-installation-steps.sh: 5: /vagrant/final-installation-steps.sh: function: not found
: not foundnal-installation-steps.sh: 9: /vagrant/final-installation-steps.sh:
/vagrant/final-installation-steps.sh: 24: /vagrant/final-installation-steps.sh: Syntax error: "(" unexpected (expecting "then")
```

I'll continue to test with ASpace outside of the virtual box setup but just thought I'd pass this along in case others try to set things up with vagrant and perhaps run into a similar issue.

**Comment by rsdoiel** [comment]
Let me look into that. Robert

**Comment by rsdoiel** [comment]
Try 

``` shell
     /vagrant/final-installation-stops.sh
```

It should already be executable. If you run it with a real "sh" then you'll get errors. This is a bash script. That might be the problem. If not I can look deeper.

**Comment by rsdoiel** [comment]
I found a typo in finial-installation-steps.sh. I think I must have hit a backspace at some point. I have corrected it so there is a space between ';' and the word then in one of the functions. Just pushed changes to master

**Comment by fordmadox** [comment]
Yeah, I tried to run it a number of different ways the first time around with no luck.  I tried the new version, again with no luck. 

I finally opened up the file with Vi, and that showed that the only problem was with the line break characters, which was introduced originally since I cloned the repo to a Windows laptop.  I replaced those line breaks with this command in Vi, :%s/\r/\r/g, and I think everything updated fine after that (although I ignored a GNU GRUB message, so I'm not entirely sure).

I then had to install java, so I selected 1.8.  At this point, everything seemed to start up okay, but I nevertheless got a few errors before the ASpace backend came up.  I'm not sure if that had anything to do with this section of the readme file, "Currently, if you want to use Java 1.8, you will need to remove the jdt-compiler jar library from the java classpath ( lib directory of your ArchivesSpace directory)." or something else.  One of the messages was being unable to connect to the database, but I verified that your script installed the mysql connector file in the archivesspace/lib directory, so that shouldn't the problem.

Anyhow, I'll try this tomorrow on a Mac laptop, and I imagine that everything will go smoothly.  Still, I'd like to get it working on my Windows machine, as well, since using Virtual Box on there is the only way that I'm currently able to start up a dev instance of ArchivesSpace without using Mac or Linux.

But, if all else fails, it really only takes a few minutes to get ASpace up and running on a Windows machine with the embedded database.

**Comment by rsdoiel** [comment]
Originally  I think you tried.

``` shell
     sh /vagrant/final-installation-steps.sh
```

That's the original BSD _sh_ which doesn't support functions in scripts (and some other things I rely on from time to time).  Maybe I should rename it /vagrant/final-installation-steps.bash to be clear.  Sharing a file extension does cause confusion.  

You can run the script two ways

``` shell
    bash /vagrant/final-installation-steps.sh
```

(Note this is Bash not "sh")

Or because the script is executable (775 for permissions) and the bang line correctly points to Bash

``` shell
    /vagrant/final-installation-steps.sh
```

If the script fails you'll be left with a half setup machine which is no end of grief.  In that case I recommend from your local machine (not the vagrant instance)

``` shell
   vagrant destroy -f
   vagrant up
   vagrant ssh
```

From the new vagrant instance

``` shell
    /vagrant/final-installation-steps.sh
```

For me this works on both my work Mac OS X desktop and my Ubuntu 16.06 LTS laptop.  Not sure about windows as I only run windows via Virtual Box on my work Mac for testing.

For the workshop I have asked Christina to provide ArchivesSpace instances for each participant during the workshop.  I really included the vagrant stuff as a Plan B if that fell through or people want to play with this presentation outside the workshop.

Sorry for the trouble with Vagrant.

Going to take a break for a bit and be back on line later.

**Comment by fordmadox** [comment]
I finally got everything set up, but I'm not sure how to address the issues I had on Windows.  Anyway, here's what I did, and now ASpace is running without any problems with vagrant:
1. This time I used Notepad++ and removed the Windows line breaks by going to Edit --> EOL Conversion --> Unix/OSX Format.  I had hoped that would be the only step, but there were a few more bumps in the road (at least for me!).  Anyhow, I could then run your final steps script fine after connecting to the new server with SSH, which I did with the Windows Git Command client.
2. This time, when the GNU GBUB warning came up, I actually selected an option using the spacebar (thanks to this post!: http://askubuntu.com/questions/384388/how-to-select-option-in-configuration-grub-pc-menu)
3. Everything was installing fine, but when MySQL asked me if I wanted to add a password for the root user, I opted to do so.  I don't know if this was the reason or not, but the blank archivesspace database and the 'as' user weren't created before the script finished.  Anyhow, this was easy enough to do, so I did that on my own after the fact.
4. I then re-ran ASpace's setup-database.sh script.
5. At last, I thought, everything should work, but I noticed that the ASpace start-up script was complaining that it couldn't write to the logs, compile the Jasper files, etc.  Recognizing that this a permissions problem, I opened your script and re-ran this line:  "sudo chown -R vagrant:archivesspace /archivesspace" (after verifying that the users and groups were created successfully).  Then, everything started up fine.

I didn't dig any deeper to see if the Windows line break issues or the fact that I added a root password for MySQL caused any other issues during my install, but I'm at least able to start up ASpace now on the virtual server and run the python scripts against the API.

Not sure if any of that helps, but I hope so.  Anyhow, I'll go through the whole workshop again later near the end of the week.

**Comment by rsdoiel** [comment]
Sounds good. Line breaks can be the issue. I setup the MySQL stuff early
and don't expect it to be password protected (not what I recommend if your
on a sprint shared network even for dev and testing). The script certainly
can be improved but not a high priority. Touch base later in the week.
Happy Hacking!  Robert

**Comment by rsdoiel** [comment]
I finally got the agent example working.  I really wish they didn't drop the curl examples from the API docs...  Anyhow I have been thinking about the Vagrant stuff. Maybe I should cut it and just point to the official install docs and leave it at that. What do you think?

**Comment by rsdoiel** [comment]
I think pointing at the ArchivesSpace installation instructions is the long term solution. Added that to the presentation and closing this issue.
